config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from config.views import index

urlpatterns = [
    path("admin/", admin.site.urls),
    path("posts/", include("posts.urls")),
    path("users/", include("users.urls")),
    path("", index),
]
urlpatterns += static(
    prefix=settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT,
)

posts/urls.py
from django.urls import path

from posts.views import feeds, comment_add, comment_delete

urlpatterns = [
    path("feeds/", feeds),
    path("comment_add/", comment_add),
    path("comments/<int:comment_id>/delete/", comment_delete),
]

users/urls.py
from django.urls import path

from users.views import login_view, logout_view, signup

urlpatterns = [
    path("login/", login_view),
    path("logout/", logout_view),
    path("signup/", signup),
]

posts/models.py
from django.db import models


class Post(models.Model):
    user = models.ForeignKey("users.User", verbose_name="작성자", on_delete=models.CASCADE)
    content = models.TextField("내용", blank=True)
    created = models.DateTimeField("작성일시", auto_now_add=True)


class PostImage(models.Model):
    post = models.ForeignKey(Post, verbose_name="포스트", on_delete=models.CASCADE)
    photo = models.ImageField("사진", upload_to="post")


class Comment(models.Model):
    user = models.ForeignKey("users.User", verbose_name="작성자", on_delete=models.CASCADE)
    post = models.ForeignKey(Post, verbose_name="포스트", on_delete=models.CASCADE)
    content = models.TextField("내용")
    created = models.DateTimeField("작성일시", auto_now_add=True)

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    profile_image = models.ImageField("프로필 이미지", upload_to="users/profile", blank=True)
    short_description = models.TextField("소개글", blank=True)
    like_posts = models.ManyToManyField(
        "posts.Post",
        verbose_name="좋아요 누른 Post목록",
        related_name="like_users",
        blank=True,
    )

    def __str__(self):
        return self.username

posts/forms.py
from django import forms

from posts.models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = [
            "post",
            "content",
        ]
        widgets = {
            "content": forms.Textarea(
                attrs={
                    "placeholder": "댓글 달기...",
                }
            )
        }

users/forms.py
from django import forms
from django.core.exceptions import ValidationError

from users.models import User


class LoginForm(forms.Form):
    username = forms.CharField(
        min_length=3,
        widget=forms.TextInput(
            attrs={"placeholder": "사용자명 (3자리 이상)"},
        ),
    )
    password = forms.CharField(
        min_length=4,
        widget=forms.PasswordInput(
            attrs={"placeholder": "비밀번호 (4자리 이상)"},
        ),
    )


class SignupForm(forms.Form):
    username = forms.CharField()
    password1 = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(widget=forms.PasswordInput)
    profile_image = forms.ImageField()
    short_description = forms.CharField()

    def clean_username(self):
        username = self.cleaned_data["username"]
        if User.objects.filter(username=username).exists():
            raise ValidationError(f"입력한 사용자명({username})은 이미 사용중입니다")
        return username

    def clean(self):
        password1 = self.cleaned_data["password1"]
        password2 = self.cleaned_data["password2"]
        if password1 != password2:
            self.add_error("password2", "비밀번호와 비밀번호 확인란의 값이 다릅니다")

    def save(self):
        username = self.cleaned_data["username"]
        password1 = self.cleaned_data["password1"]
        profile_image = self.cleaned_data["profile_image"]
        short_description = self.cleaned_data["short_description"]
        user = User.objects.create_user(
            username=username,
            password=password1,
            profile_image=profile_image,
            short_description=short_description,
        )
        return user

config/views.py
from django.shortcuts import redirect


def index(request):
    if request.user.is_authenticated:
        return redirect("/posts/feeds/")
    else:
        return redirect("/users/login2/")

posts/views.py
from django.shortcuts import render, redirect

from posts.models import Post


def feeds(request):
    user = request.user
    if not user.is_authenticated:
        return redirect("/users/login/")

    posts = Post.objects.all()
    context = {"posts": posts}
    return render(request, "posts/feeds.html", context)

users/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect

from users.forms import LoginForm, SignupForm


def login_view(request):
    if request.user.is_authenticated:
        return redirect("/posts/feeds/")

    if request.method == "POST":
        form = LoginForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            user = authenticate(username=username, password=password)

            if user:
                login(request, user)
                return redirect("/posts/feeds/")
            else:
                form.add_error(None, "입력한 자격증명에 해당하는 사용자가 없습니다.")

        context = {"form": form}
        return render(request, "users/login.html", context)
    else:
        form = LoginForm()
        context = {"form": form}
        return render(request, "users/login.html", context)


def logout_view(request):
    logout(request)
    return redirect("/users/login/")


def signup(request):
    if request.method == "POST":
        form = SignupForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect("/posts/feeds/")
    else:
        form = SignupForm()

    context = {"form": form}
    return render(request, "users/signup.html", context)

templates/_base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Pystagram</title>
    {% block head %}{% endblock %}
</head>
<body>
    {% block base_content %}{% endblock %}
</body>
</html>

templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    {% block content %}
    {% endblock %}
</body>
</html>

templates/base_nav.html
{% extends '_base.html' %}

{% block base_content %}
    {% include 'nav.html' %}
    {% block content %}{% endblock %}
{% endblock %}

templates/base_profile.html
{% extends 'base_nav.html' %}

{% block content %}
<div id="profile">
    <div class="info">
        <!-- 프로필 이미지 영역 -->
        {% if user.profile_image %}
            <img src="{{ user.profile_image.url }}">
        {% endif %}

        <!-- 사용자 정보 영역 -->
        <div class="info-texts">
            <h1>{{ user.username }}</h1>
            <div class="counts">
                <dl>
                    <dt>Posts</dt>
                    <dd>
                        <a href="{% url 'users:profile' user_id=user.id %}">{{ user.post_set.count }}</a>
                    </dd>
                    <dt>Followers</dt>
                    <dd>
                        <a href="{% url 'users:followers' user_id=user.id %}">{{ user.followers.count }}</a>
                    </dd>
                    <dt>Following</dt>
                    <dd>
                        <a href="{% url 'users:following' user_id=user.id %}">{{ user.following.count }}</a>
                    </dd>
                </dl>
            </div>
            <p>{{ user.short_description }}</p>
        </div>
    </div>
    {% block bottom_data %}{% endblock %}
</div>
{% endblock %}

templates/base_slider.html
{% extends '_base.html' %}
{% load static %}

{% block head %}
    <link href="{% static 'splide/splide.css' %}" rel="stylesheet">
    <script src="{% static 'splide/splide.js' %}"></script>
{% endblock %}

{% block base_content %}
    {% include 'nav.html' %}
    {% block content %}{% endblock %}
    <script>
        const elms = document.getElementsByClassName('splide');
        for (let i = 0; i < elms.length; i++) {
            new Splide(elms[i]).mount();
        }
    </script>
{% endblock %}

templates/nav.html
<nav>
    <h1>
        <a href="{% url 'posts:feeds' %}">Pystagram</a>
    </h1>
    <a href="{% url 'posts:post_add' %}">Add post</a>
    <a href="{% url 'users:logout' %}">Logout</a>
</nav>

templates/posts/feeds.html
{% extends 'base.html' %}

{% block content %}
<nav>
    <h1>
        <a href="/posts/feeds/">Pystagram</a>
    </h1>
    <a href="/users/logout/">Logout</a>
</nav>
<div id="feeds" class="post-container">
    <!-- 전달된 Post QuerySet객체를 순회 -->
    {% for post in posts %}
    <article class="post">
        <header class="post-header">
            {% if post.user.profile_image %}
                <img src="{{ post.user.profile_image.url }}">
            {% endif %}
            <span>{{ post.user.username }}</span>
        </header>

        <!-- 이미지 슬라이드 영역 시작 -->
        <div class="post-images splide">
            <div class="splide__track">
                <ul class="splide__list">
                    {% for image in post.postimage_set.all %}
                        {% if image.photo %}
                            <li class="splide__slide">
                                <img src="{{ image.photo.url }}">
                            </li>
                        {% endif %}
                    {% endfor %}
                </ul>
            </div>
        </div>
        <!-- 이미지 슬라이드 영역 종료 -->

        <div class="post-content">
            {{ post.content|linebreaksbr }}
        </div>

        <div class="post-buttons">
            <button>Likes(0)</button>
            <span>Comments(0)</span>
        </div>

        <div class="post-comments">
            <ul>
                <!-- 각 Post에 연결된 PostComment들을 순회 -->
                {% for comment in post.comment_set.all %}
                    <li>
                        <span>{{ comment.user.username }}</span>
                        <span>{{ comment.content }}</span>
                    </li>
                {% endfor %}
            </ul>
        </div>

        <small>{{ post.created }}</small>
        <div class="post-comment-create">
            <input type="text" placeholder="댓글 달기...">
            <button type="submit">게시</button>
        </div>
    </article>
    {% endfor %}
</div>

<!-- Splide 초기화 자바스크립트 코드 -->
<script>
    const elms = document.getElementsByClassName('splide');
    for (let i = 0; i < elms.length; i++) {
        new Splide(elms[i]).mount();
    }
</script>
{% endblock %}

templates/posts/post.html
<article id="post-{{ post.id }}" class="post">
    <header class="post-header">
        {% if post.user.profile_image %}
        <img src="{{ post.user.profile_image.url }}">
        {% endif %}
        <span>{{ post.user.username }}</span>
    </header>

    <!-- 이미지 슬라이드 영역 시작 -->
    <div class="post-images splide">
        <div class="splide__track">
            <ul class="splide__list">
                {% for image in post.postimage_set.all %}
                {% if image.photo %}
                <li class="splide__slide">
                    <img src="{{ image.photo.url }}">
                </li>
                {% endif %}
                {% endfor %}
            </ul>
        </div>
    </div>
    <!-- 이미지 슬라이드 영역 종료 -->

    <div class="post-content">
        {{ post.content|linebreaksbr }}
        <div class="post-tags">
            {% for tag in post.tags.all %}
            <a href="{% url 'posts:tags' tag_name=tag.name %}">#{{ tag.name }}</a>
            {% endfor %}
        </div>
    </div>

    <div class="post-buttons">
        <button>Likes(0)</button>
        <span>Comments({{ post.comment_set.count }})</span>
    </div>

    <div class="post-comments">
        <ul>
            <!-- 각 Post에 연결된 PostComment들을 순회 -->
            {% for comment in post.comment_set.all %}
            <li>
                <span>{{ comment.user.username }}</span>
                <span>{{ comment.content }}</span>

                <!-- 댓글 삭제 Form 추가 -->
                {% if user == comment.user %}
                <form method="POST" action="{% url 'posts:comment_delete' comment_id=comment.id %}">
                    {% csrf_token %}
                    <button type="submit">삭제</button>
                </form>
                {% endif %}
            </li>
            {% endfor %}
        </ul>
    </div>

    <small>{{ post.created }}</small>
    <div class="post-comment-create">
        <form method="POST" action="{% url 'posts:comment_add' %}">
            {% csrf_token %}
            <!-- 사용자가 직접 입력하지 않는 고정된 데이터를 form내부에 위치 -->
            <input type="hidden" name="post" value="{{ post.id }}">
            {{ comment_form.content }}
            <button type="submit">게시</button>
        </form>
    </div>
</article>

templates/posts/post_add.html
{% extends 'base.html' %}

{% block content %}
<nav>
    <h1>
        <a href="/posts/feeds/">Pystagram</a>
    </h1>
    <!-- 로그아웃 링크도 함께 추가 -->
    <a href="/users/logout/">Logout</a>
</nav>
<div id="container">
    <div id="post-add">
        <h1>Post 작성</h1>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div>
                <!-- label의 for속성에는 가리키는 input의 id값을 입력 -->
                <label for="id_images">이미지</label>
                <input id="id_images" name="images" type="file" multiple>
            </div>
            {{ form.as_p }}
            <button type="submit">게시</button>
        </form>
    </div>
</div>
{% endblock %}

templates/posts/post_detail.html
{% extends 'base.html' %}

{% block content %}
{% include 'nav.html' %}
<div id="feeds" class="post-container">
    {% include 'posts/post.html' %}
</div>

<!-- Splide 초기화 자바스크립트 코드 -->
<script>
    const elms = document.getElementsByClassName('splide');
    for (let i = 0; i < elms.length; i++) {
        new Splide(elms[i]).mount();
    }
</script>
{% endblock %}

templates/posts/tags.html
{% extends 'base.html' %}

{% block content %}
<nav>
    <h1>
        <a href="{% url 'posts:feeds' %}">Pystagram</a>
    </h1>
    <a href="{% url 'posts:post_add' %}">Add post</a>
    <a href="{% url 'users:logout' %}">Logout</a>
</nav>
<div id="tags">
    <header class="tags-header">
        <h2>#{{ tag_name }}</h2>
        <div>게시물 {{ posts.count }}</div>
    </header>
    <div class="post-grid-container">
        {% for post in posts %}
            {# Post에 연결된 PostImage가 있으며, 연결된 첫 번째 PostImage의 photo가 비어있지 않은 경우 #}

            {% if post.postimage_set.first and post.postimage_set.first.photo %}
                <div class="post-grid">
                    <img src="{{ post.postimage_set.first.photo.url }}">
                </div>
            {% endif %}
        {% empty %}
            <p>검색된 게시물이 없습니다</p>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/users/followers.html
{% extends 'base_profile.html' %}

{% block bottom_data %}
<div class="relationships">
    <h3>Followers</h3>
    {% for relationship in relationships %}
        <div class="relationship">
            <a href="{% url 'users:profile' user_id=relationship.from_user.id %}">
                {% if relationship.from_user.profile_image %}
                    <img src="{{ relationship.from_user.profile_image.url }}">
                {% endif %}
                <div class="relationship-info">
                    <span>{{ relationship.from_user.username }}</span>
                    <span>{{ relationship.created|date:"y.m.d" }}</span>
                </div>
            </a>
        </div>
    {% endfor %}
</div>
{% endblock %}

templates/users/following.html
{% extends 'base_profile.html' %}

{% block bottom_data %}
<div class="relationships">
    <h3>Following</h3>
    {% for relationship in relationships %}
        <div class="relationship">
            <a href="{% url 'users:profile' user_id=relationship.to_user.id %}">
                {% if relationship.to_user.profile_image %}
                    <img src="{{ relationship.to_user.profile_image.url }}">
                {% endif %}
                <div class="relationship-info">
                    <span>{{ relationship.to_user.username }}</span>
                    <span>{{ relationship.created|date:"y.m.d" }}</span>
                </div>
            </a>
        </div>
    {% endfor %}
</div>
{% endblock %}

templates/users/login.html
{% extends 'base.html' %}

{% block content %}
<div id="login">
    <form method="POST">
        <h1>Pystagram</h1>
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-login">로그인</button>
        <a href="/users/signup/">회원가입 페이지로 이동</a>
    </form>
</div>
{% endblock %}}

templates/users/profile.html
{% extends 'base_nav.html' %}

{% block content %}
<div id="profile">
    <div class="info">
        <!-- 프로필 이미지 영역 -->
        {% if user.profile_image %}
            <img src="{{ user.profile_image.url }}">
        {% endif %}

        <!-- 사용자 정보 영역 -->
        <div class="info-texts">
            <h1>{{ user.username }}</h1>
            <div class="counts">
                <dl>
                    <dt>Posts</dt>
                    <dd>{{ user.post_set.count }}</dd>
                    <dt>Followers</dt>
                    <dd>{{ user.followers.count }}</dd>
                    <dt>Following</dt>
                    <dd>{{ user.following.count }}</dd>
                </dl>
            </div>
            <p>{{ user.short_description }}</p>
        </div>
    </div>

    <!-- 사용자가 작성한 Post목록 -->
    <div class="post-grid-container">
        {% for post in user.post_set.all %}
            {% if post.postimage_set.first %}
                {% if post.postimage_set.first.photo %}
                    <div class="post-grid">
                        <a href="{% url 'posts:post_detail' post_id=post.id %}">
                            <img src="{{ post.postimage_set.first.photo.url }}" alt="">
                        </a>
                    </div>
                {% endif %}
            {% endif %}
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/users/signup.html
{% extends 'base.html' %}

{% block content %}
<div id="signup">
    <form method="POST" enctype="multipart/form-data">
        <h1>Pystagram</h1>
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-signup">가입</button>
        <a href="/users/login/">로그인 페이지로 이동</a>
    </form>
</div>
{% endblock %}